### ISSUE TITLE
PDFs prontos a impressão

### ISSUE THREAD

**Issue by marado** [nmcastro/ansol-flyerA5-socios#1]
Criar PDFs para impressão (formato A4) com os flyers (duas páginas, para ser frente e verso; dois flyers por folha, para depois serem guilhotinadas).

Fazê-lo tanto para as versões a cores e a preto-e-branco.

Estes PDFs são particularmente úteis para fazer a impressão dos flyers numa gráfica.

**Comment by nmcastro** [comment]
Os ficheiros estão agora disponíveis na pasta 'pdf'.
c0bb5f1716e685a5ab4d25e8ea9d9ffc9bcc0f94
