### ISSUE TITLE
QR Codes ilegíveis

### ISSUE THREAD

**Issue by marado** [nmcastro/ansol-flyerA5-socios#3]
Aparentemente os QR Codes são ilegíveis (tentado em digital/ecrã e papel, versões cores e b&w, com dois programas diferentes). Provavelmente causado pelas cores (o software deve estar à procura de preto e branco, não branco e azul nem cinzentos...).

**Comment by nmcastro** [comment]
Ver 8ba40261674ad16c29cde32c54b88e1994228199. 
Os novos ficheiros dispõem de um código QR no canto inferior direito, gerado no Inkscape.
Foram realizados testes em suporte digital com a ferramenta [Barcode Scanner](https://f-droid.org/repository/browse/?fdid=com.google.zxing.client.android).

Uma vez que ainda não realizei testes em suporte de papel, vou manter este issue **aberto**.

Fica um screenshot dos resultados dos testes em suporte digital (foi semelhante em todos os casos).

[!Screenshot do resultado da leitura dos códigos QR](https://github.com/nmcastro/ansol-flyerA5-socios/blob/master/Screenshot_2016-08-02-00-56-51.png)

**Comment by marado** [comment]
Não sou muito fã da solução arranjada, visualmente, mas parece funcionar :-) Obrigado.

**Comment by nmcastro** [comment]
Acabei por não ter oportunidade de imprimir os flyers para testar o código. Por outro lado, eu próprio não estou totalmente satisfeito com a solução que lhes dei, visualmente. Realmente, há espaço para melhorar um bocado!

Consegues descrever-me aquilo que não te agrada? Tens alguma sugestão? Entretanto, vou procurar outros arranjos gráficos :)

**Comment by marado** [comment]
Não tenho a certeza, sem tentar visualmente, mas diria que se podia tentar manter o posicionamento original do QR, apenas com as "novas cores"...

**Comment by nmcastro** [comment]
Com a correcção da cor, criei outro arranjo. Segui o primeiro que tinha. Estou mais satisfeito! Vê o commit d16eb0e3dbca591d8e2af41fe5c7e07caf8f2f9f

**Comment by marado** [comment]
Gostei, e funciona.

**Comment by nmcastro** [comment]
A versão em b&w foi também remodelada de acordo com a versão a cores.
