### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by marado** [nmcastro/ansol-flyerA5-socios#7]
It would be really nice if these materials had a free license. I'll let you decide which you prefer, tho :-)

**Comment by nmcastro** [comment]
I've added the Creative Commons Attribution-ShareAlike 4.0 International License. I believe that this license is more suitable for graphic work and complies with the standards defined in the GPL lv3 :).

The legal text of the license is available in the LICENSE.txt file, which was added in c4d98e510395d07e31727627fc7fe8155aecbf63

I will close this issue :)
